blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    # path('detail/<int:pk>', views.blog_view, name='post_url'),
    # path('detail/<str:title>', views.blog_view, name='post_url'),
    path('detail/<slug:slug>', views.blog_view, name='post_url'),
    path('list', views.post_list, name='post_list_url'),
    path('category/<int:pk>', views.category_detail, name='category_list_url'),
    path('search', views.search, name='search_url'),
    path('contact', views.contact, name='contact_page_url')
]

home/urls.py
from django.urls import path
from . import views

app_name = "home"

urlpatterns = [
    path('', views.home, name='home_url')
]

standblog_r/urls.py
from django.contrib import admin
from django.urls import path, include
# static and media files
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('', include('account.urls')),
    path('articles/', include('blog.urls'), name='blog_articles'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/views.py
from django.shortcuts import render
from blog.models import Article


def home(request):
    """ home page function"""
    # articles = Article.objects.all()
    # use querySet and filter
    # articles = Article.objects.filter(status=True)
    articles = Article.objects.publish()    # func name
    # recent_articles = Article.objects.all()[:3]
    context = {
        'articles': articles,
        # 'recent_articles': recent_articles,
        'navbar': 'home',
    }
    return render(request, "home/index.html", context)

home/templates/home/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %}home{% endblock %}

{% block content %}

    <!-- Page Content -->
    <!-- Banner Starts Here -->
    <div class="main-banner header-text">
        <div class="container-fluid">
            <div class="owl-banner owl-carousel">
                {# display articles #}
                {% for article in articles %}

                    <div class="item">
                        <img src="{{ article.image.url }}" alt="{{ article.title }}">
                        <div class="item-content">
                            <div class="main-content">
                                <div class="meta-category">
                                    <span>{{ article.category.first.title }}</span>
                                </div>
                                {#                                <a href="{% url 'blog:post_url' article.id %}"><h4>{{ article.title }}</h4></a>#}
                                <a href="{{ article.get_absolute_url }}"><h4>{{ article.title }}</h4></a>
                                <ul class="post-info">
                                    <li><a href="#">{{ article.author.username }}</a></li>
                                    <li><a href="#">{{ article.created }}</a></li>
                                    <li><a href="#">72 Comments</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
    <!-- Banner Ends Here -->

    {% include 'shared/banner.html' %}


    <section class="blog-posts">
        <div class="container">
            <div class="row">
                <div class="col-lg-8">
                    <div class="all-blog-posts">
                        <div class="row">
                            {% for article in recent_articles %}
                                <div class="col-lg-12">
                                    <div class="blog-post">
                                        <div class="blog-thumb">
                                            <img src="{{ article.image.url }}" alt="">
                                        </div>
                                        <div class="down-content">
                                            <span>Lifestyle</span>
                                            <a href="{{ article.get_absolute_url }}"><h4>{{ article.title }}</h4></a>
                                            <ul class="post-info">
                                                <li><a href="#">{{ article.author }}</a></li>
                                                <li><a href="#">{{ article.created }}</a></li>
                                                <li><a href="#">12 Comments</a></li>
                                            </ul>
                                            <p>{{ article.body }}</p>
                                            <div class="post-options">
                                                <div class="row">
                                                    <div class="col-6">
                                                        <ul class="post-tags">
                                                            <li><i class="fa fa-tags"></i></li>
                                                            <li><a href="#">Beauty</a>,</li>
                                                            <li><a href="#">Nature</a></li>
                                                        </ul>
                                                    </div>
                                                    <div class="col-6">
                                                        <ul class="post-share">
                                                            <li><i class="fa fa-share-alt"></i></li>
                                                            <li><a href="#">Facebook</a>,</li>
                                                            <li><a href="#"> Twitter</a></li>
                                                        </ul>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            {% endfor %}

                        </div>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="sidebar">
                        <div class="row">

                            {# recent posts #}
                            {% include 'shared/sidebar.html' %}

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>



{% endblock %}