account/urls.py
from django.urls import path
from . import views

app_name = "account"

urlpatterns = [
    path('login', views.login_view, name='login_url'),
    path('logout', views.logout_view, name='logout_url'),
    path('register', views.register_view, name='register_url'),
]

blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    # path('detail/<int:pk>', views.blog_view, name='post_url'),
    # path('detail/<str:title>', views.blog_view, name='post_url'),
    path('detail/<slug:slug>', views.blog_view, name='post_url'),
    path('list', views.post_list, name='post_list_url'),
    path('category/<int:pk>', views.category_detail, name='category_list_url'),
    path('search', views.search, name='search_url'),
    path('contact', views.contact, name='contact_page_url')
]

home/urls.py
from django.urls import path
from . import views

app_name = "home"

urlpatterns = [
    path('', views.home, name='home_url')
]

standblog_r/urls.py
from django.contrib import admin
from django.urls import path, include
# static and media files
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('', include('account.urls')),
    path('articles/', include('blog.urls'), name='blog_articles'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/shared/banner.html
<section class="call-to-action">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="main-content">
                    <div class="row">
                        <div class="col-lg-8">
                            <span>Best environment to share your ideas.</span>
                            <h4>Stay creative :)</h4>
                        </div>
                        <div class="col-lg-4">
                            <div class="main-button">
                                <a rel="nofollow" href="https://templatemo.com/tm-551-stand-blog" target="_parent">join
                                    us</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

templates/shared/foot_ref.html
{% load static %}
<!-- Bootstrap core JavaScript -->
<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>


<!-- Additional Scripts -->
<script src="{% static 'js/custom.js' %}"></script>
<script src="{% static 'js/owl.js' %}"></script>
<script src="{% static 'js/slick.js' %}"></script>
<script src="{% static 'js/isotope.js' %}"></script>
<script src="{% static 'js/accordions.js' %}"></script>


<script language="text/Javascript">
    cleared[0] = cleared[1] = cleared[2] = 0; //set a cleared flag for each field
    function clearField(t) {                   //declaring the array outside of the
        if (!cleared[t.id]) {                      // function makes it static and global
            cleared[t.id] = 1;  // you could use true and false, but that's more typing
            t.value = '';         // with more chance of typos
            t.style.color = '#fff';
        }
    }
</script>

templates/shared/footer.html
{% load static %}

<footer>
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <ul class="social-icons">
                    <li><a href="#">Facebook</a></li>
                    <li><a href="#">Twitter</a></li>
                    <li><a href="#">Behance</a></li>
                    <li><a href="#">Linkedin</a></li>
                    <li><a href="#">Dribbble</a></li>
                </ul>
            </div>
            <div class="col-lg-12">
                <div class="copyright-text">
                    <p>Copyright 2020 Stand Blog Co.

                        | Design: <a rel="nofollow" href="https://templatemo.com" target="_parent">TemplateMo</a></p>
                </div>
            </div>
        </div>
    </div>
</footer>

templates/shared/head_ref.html
{% load static %}

<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta name="description" content="">
<meta name="author" content="">
<link href="https://fonts.googleapis.com/css?family=Roboto:100,100i,300,300i,400,400i,500,500i,700,700i,900,900i&display=swap"
      rel="stylesheet">

<title>{% block title %}{% endblock %}</title>

<!-- Bootstrap core CSS -->
<link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">


<!-- Additional CSS Files -->
<link rel="stylesheet" href="{% static 'css/fontawesome.css' %}">
<link rel="stylesheet" href="{% static 'css/templatemo-stand-blog.css' %}">
<link rel="stylesheet" href="{% static 'css/owl.css' %}">

templates/shared/header.html
{% load static %}
<!-- Header -->
<header class="">
    <nav class="navbar navbar-expand-lg">
        <div class="container">
            <a class="navbar-brand" href="{% url 'home:home_url' %}"><h2>Stand Blog<em>.</em></h2></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                    aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a class="nav-link {% if request.resolver_match.url_name == 'home_url' %}active{% endif %}"
                           href="{% url 'home:home_url' %}">Home
                            <span class="sr-only">(current)</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link  {% if request.resolver_match.url_name == 'about' %}active{% endif %}"
                           href="about.html">About Us</a>
                    </li>
                    <li class="nav-item ">
                        <a class="nav-link  {% if request.resolver_match.url_name == 'post_list_url' %}active{% endif %}"
                           href="{% url 'blog:post_list_url' %}">Blog Entries</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link  {% if request.resolver_match.url_name == 'post_url' %}active{% endif %}"
                           href="post-details.html">Post Details</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link  {% if request.resolver_match.url_name == 'contact_page_url' %}active{% endif %}"
                           href="{% url 'blog:contact_page_url' %}">Contact Us</a>
                    </li>
                    {# show login button on navbar #}
                    <li class="nav-item">
                        {% if request.user.is_authenticated %}
                            {# set a default user image #}
                            {% if user.profile.user_image %}
                                <span>
                                <img src="{{ user.profile.user_image.url }}" width="40px" height="40px"
                                     style="border-radius: 100%" alt="{{ user.profile.user }}">
                                </span>
                            {% else %}
                                <span>
                                <img src="{% static 'images/icons/default-profile-icon.jpg' %}" width="40px"
                                     height="40px"
                                     style="border-radius: 100%" alt="{{ user.profile.user }}">
                                </span>
                            {% endif %}
                            {#                            <a class="nav-link" href="{% url 'home:home_url' %}">{{ request.user.username }}</a>#}
                            <a class="nav-link" href="{% url 'home:home_url' %}">{{ user.profile.user }}</a>
                        {% else %}
                            <a class="nav-link" href="{% url 'account:login_url' %}">Login</a>
                        {% endif %}
                    </li>
                    {#  #}
                    <li class="nav-item">
                        {% if request.user.is_authenticated %}
                            <a class="nav-link" href="{% url 'account:logout_url' %}">Logout</a>
                        {% else %}
                            <a class="nav-link" href="{% url 'account:register_url' %}">Register</a>
                        {% endif %}
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>

templates/shared/sidebar.html
{# search #}
<div class="col-lg-12">
    <div class="sidebar-item search">
        <form id="search_form" name="gs" method="GET" action="{% url 'blog:search_url' %}">
            {% if request.GET.q %}
                <input type="text" name="q" class="searchText" placeholder="type to search..."
                   autocomplete="on" value="{{ request.GET.q }}">
            {% else %}
                <input type="text" name="q" class="searchText" placeholder="type to search..."
                   autocomplete="on">
            {% endif %}

        </form>
    </div>
</div>

{# recent posts #}
<div class="col-lg-12">
    <div class="sidebar-item recent-posts">
        <div class="sidebar-heading">
            <h2>Recent Posts</h2>
        </div>
        <div class="content">
            <ul>
                {% for item in recent_articles %}
                    <li><a href="{{ item.get_absolute_url }}">
                        <h5>{{ item.title }}</h5>
                        <span>{{ item.created }}</span>
                    </a></li>

                {% endfor %}
            </ul>
        </div>
    </div>
</div>
{# categories #}
<div class="col-lg-12">
    <div class="sidebar-item categories">
        <div class="sidebar-heading">
            <h2>Categories</h2>
        </div>
        <div class="content">
            <ul>
                {% for item in categories %}
                    <li><a href="{% url 'blog:category_list_url' item.id %}">{{ item.title }}</a></li>
                {% endfor %}
            </ul>
        </div>
    </div>
</div>
{# hot tags #}
<div class="col-lg-12">
    <div class="sidebar-item tags">
        <div class="sidebar-heading">
            <h2>Tag Clouds</h2>
        </div>
        <div class="content">
            <ul>
                <li><a href="#">Lifestyle</a></li>
                <li><a href="#">Creative</a></li>
                <li><a href="#">HTML5</a></li>
                <li><a href="#">Inspiration</a></li>
                <li><a href="#">Motivation</a></li>
                <li><a href="#">PSD</a></li>
                <li><a href="#">Responsive</a></li>
            </ul>
        </div>
    </div>
</div>